---
- name: copy index.html file
  copy:
   src: index1.html
   dest: /var/www/html/index.html
   owner: root
   group: root
   mode: 0644
  when: inventory_hostname == "server1"
- name: copy index.html file
  copy:
   src: index2.html
   dest: /var/www/html/index.html
   owner: root
   group: root
   mode: 0644
  when:  inventory_hostname == "server2"

