---
- name: restart haproxy
  systemd:
    state: restarted
    daemon_reload: yes
    name: haproxy
- name: restart httpd
  systemd:
    state: restarted
    daemon_reload: yes
    name: httpd
- name: restart apache2
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2


